name: umeng_analytics_with_push_platform_interface
description: A common platform interface for the u-analytics, u-push plugin.
version: 0.0.1
homepage: https://github.com/wangbo4020/flutter-plugins/tree/main/packages/umeng_analytics_with_push/umeng_analytics_with_push

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.11.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"